export const OBTENER_AFILIADOS = 'OBTENER_AFILIADOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PRINCIPIO = 'PRINCIPIO';
export const INICIO_LISTO = 'INICIO_LISTO';
export const TIPO_LISTO = 'TIPO_LISTO';
export const INFO_LISTO = 'INFO_LISTO';
export const TALLER_LISTO = 'TALLER_LISTO';
export const AFILIADOID = 'AFILIADOID';
export const CITA_LISTA = 'CITA_LISTA';
export const IMGS_LISTO = 'IMGS_LISTO';
export const OBTENER_AFILIADOID = 'OBTENER_AFILIADOID';
export const ASIGNAR_HORA = 'ASIGNAR_HORA';
export const ASIGNAR_FECHA = 'ASIGNAR_FECHA';
export const REGISTRAR_ARTICULO = 'REGISTRAR_ARTICULO';
export const QUITAR_REGISTRO = 'QUITAR_REGISTRO';

export const OBTENER_ARTICULOS_USUARIO = 'OBTENER_ARTICULOS_USUARIO'
export const OBTENER_ARTICULO = 'OBTENER_ARTICULO';
export const ARTICULO_ACTUAL = 'ARTICULO_ACTUAL';
export const ELIMINAR_ARTICULO = 'ELIMINAR_ARTICULO';


export const ARTICULO_VALORADO = 'ARTICULO_VALORADO';
export const AGREGAR_VALORADO = 'AGREGAR_VALORADO';
export const VALIDAR_VALORADO = 'VALIDAR_VALORADO';
export const ELIMINAR_VALORADO = 'ELIMINAR_VALORADO';
export const ESTADO_VALORADO = 'ESTADO_VALORADO';
export const VALORADO_ACTUAL = 'VALORADO_ACTUAL';
export const ACTUALIZAR_VALORADO = 'ACTUALIZAR_VALORADO';
export const LIMPIAR_VALORADO = 'LIMPIAR_VALORADO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'; 
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'; 

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';