export const OBTENER_AFILIADOS = 'OBTENER_AFILIADOS';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const PRINCIPIO = 'PRINCIPIO';
export const INICIO_LISTO = 'INICIO_LISTO';
export const TIPO_LISTO = 'TIPO_LISTO';
export const INFO_LISTO = 'INFO_LISTO';
export const TALLER_LISTO = 'TALLER_LISTO';
export const AFILIADOID = 'AFILIADOID';
export const CITA_LISTA = 'CITA_LISTA';
export const IMGS_LISTO = 'IMGS_LISTO';
export const OBTENER_AFILIADOID = 'OBTENER_AFILIADOID';
export const ASIGNAR_HORA = 'ASIGNAR_HORA';
export const ASIGNAR_FECHA = 'ASIGNAR_FECHA';
export const REGISTRAR_ARTICULO = 'REGISTRAR_ARTICULO';
export const QUITAR_REGISTRO = 'QUITAR_REGISTRO';

export const OBTENER_ARTICULOS_USUARIO = 'OBTENER_ARTICULOS_USUARIO'
export const OBTENER_ARTICULOID = 'OBTENER_ARTICULOID';
export const EDITAR_ARTICULO = 'EDITAR_ARTICULO';
export const ARTICULO_ACTUAL = 'ARTICULO_ACTUAL';
export const ELIMINAR_ARTICULO = 'ELIMINAR_ARTICULO';
export const OBTENER_ARTICULOS_AFILIADO = 'OBTENER_ARTICULOS_AFILIADO';
export const OBTENER_ARTICULOS_VALORADOS = 'OBTENER_ARTICULOS_VALORADOS';
export const INFO_ART_SELECCIONADO = 'INFO_ART_SELECCIONADO';

export const DASHBOARD = 'DASHBOARD';
export const NOTIFICACIONES = 'NOTIFICACIONES';
export const ARTICULOS = 'ARTICULOS';
export const CITAS = 'CITAS';
export const MENSAJES = 'MENSAJES';
export const FAVORITOS = 'FAVORITOS';
export const PERFIL_ARTICULO = 'PERFIL_ARTICULO';
export const PERFIL_EDITAR = 'PERFIL_EDITAR';
export const PERFIL_CONFIRMAR_ELIMINAR = 'QUITAR_ELIMINADO';
export const PERFIL_ELIMINARART = 'PERFIL_ELIMINARART';
export const PERFIL_QUITAR_ELIMINADO = 'PERFIL_QUITAR_ELIMINADO';
export const QUITAR_ELIMINADO = 'QUITAR_ELIMINADO';

export const BUSQUEDA_ARTICULOS = 'BUSQUEDA_ARTICULOS';

export const ARTICULO_VALORADO = 'ARTICULO_VALORADO';
export const AGREGAR_VALORADO = 'AGREGAR_VALORADO';
export const VALIDAR_VALORADO = 'VALIDAR_VALORADO';
export const ELIMINAR_VALORADO = 'ELIMINAR_VALORADO';
export const ESTADO_VALORADO = 'ESTADO_VALORADO';
export const VALORADO_ACTUAL = 'VALORADO_ACTUAL';
export const ACTUALIZAR_VALORADO = 'ACTUALIZAR_VALORADO';
export const LIMPIAR_VALORADO = 'LIMPIAR_VALORADO';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'; 
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'; 

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const OBTENER_NOMBRES_USUARIOS = 'OBTENER_NOMBRES_USUARIOS';
export const OBTENER_USUARIO_ID = 'OBTENER_USUARIO_ID';
export const REGISTROAF_EXITOSO = 'REGISTROAF_EXITOSO';
export const ACT_AFILIADO = 'ACT_AFILIADO';
export const RET_ACT = 'RET_ACT';
export const AFLOGIN_EXITOSO = 'AFLOGIN_EXITOSO';
export const OBTENER_AFILIADO = 'OBTENER_AFILIADO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const STOP_LOADING = 'STOP_LOADING';
export const DEF_CAT = 'DEF_CAT';

export const PERFIL_AF_DASHBOARD = 'PERFIL_AF_DASHBOARD';
export const PERFIL_AF_EDITINFO = 'PERFIL_AF_EDITINFO';
export const PERFIL_AF_VALORAR_ART = 'PERFIL_AF_VALORAR_ART';
export const PERFIL_AF_VALORADOS = 'PERFIL_AF_VALORADOS';
export const PERFIL_AF_ART_FORM_VALORAR = 'PERFIL_AF_ART_FORM_VALORAR';
export const PERFIL_AF_REMOVE_SELECTED = 'PERFIL_AF_REMOVE_SELECTED';
export const PERFIL_AF_NOTIFICACIONES = 'PERFIL_AF_NOTIFICACIONES';
export const PERFIL_AF_CITAS = 'PERFIL_AF_CITAS';
export const PERFIL_AF_MSJ = 'PERFIL_AF_MSJ';

export const CREAR_PENDIENTE = 'CREAR_PENDIENTE';
export const CREAR_VALORADO = 'CREAR_VALORADO';
export const QUITAR_VALORADO = 'QUITAR_VALORADO';
export const TRAER_VALORADOS = 'TRAER_VALORADOS';
export const TRAER_PENDIENTES = 'TRAER_PENDIENTES';
export const FILTRAR_PENDIENTES = 'FILTRAR_PENDIENTES';